database:
  sqlType: mysql
  url: tcp(mysql:3306)/raytine?charset=utf8&parseTime=true
#  url: tcp(127.0.0.1:3306)/raytine?charset=utf8&parseTime=true
  userName: root
  password: 123456
redis:
  url: redis-test:6379
#  url: 127.0.0.1:6379
  password: ""